INSERT INTO GENRE (TITLE_GENRE) VALUES ('Комедия');
INSERT INTO GENRE (TITLE_GENRE) VALUES ('Драма');
INSERT INTO GENRE (TITLE_GENRE) VALUES ('Мультфильм');
INSERT INTO GENRE (TITLE_GENRE) VALUES ('Триллер');
INSERT INTO GENRE (TITLE_GENRE) VALUES ('Документальный');
INSERT INTO GENRE (TITLE_GENRE) VALUES ('Боевик');

INSERT INTO MPA (TITLE_MPA) VALUES ('G');
INSERT INTO MPA (TITLE_MPA) VALUES ('PG');
INSERT INTO MPA (TITLE_MPA) VALUES ('PG-13');
INSERT INTO MPA (TITLE_MPA) VALUES ('R');
INSERT INTO MPA (TITLE_MPA) VALUES ('NC-17');

INSERT INTO STATUS (STATUS_NAME) VALUES ('Неподтверждена');
INSERT INTO STATUS (STATUS_NAME) VALUES ('Подтверждена');